### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by jamalnggau1** [mangoproxy-code/tgviews-gui#1]
Help.. where can i add proxy.? please give a little example sir

**Comment by mangoproxy-code** [comment]
Hi [jamalnggau1](https://github.com/jamalnggau1),

To add a proxy to the `tgviews-gui` project, you can follow these steps. Here's an example using the `requests` library in Python:

1. Clone the repository:
git clone https://github.com/mangoproxy-code/tgviews-gui.git
cd tgviews-gui

2. Install the required packages:
pip install -r requirements.txt

3. Modify the code to include the proxy settings:
Open the relevant Python script where you need to add the proxy settings. If you're making HTTP requests using the `requests` library, you can add the proxy like this:

import requests

# Define your proxy
proxies = {
    "http": "http://username:password@proxyserver:port",
    "https": "http://username:password@proxyserver:port",
}

# Make a request through the proxy
response = requests.get("http://example.com", proxies=proxies)

print(response.content)

Replace `username`, `password`, `proxyserver`, and `port` with your actual proxy credentials.

4. Run the script: After modifying the script, run it to ensure that it is using the proxy correctly.

5. Test the implementation: Make sure to test your implementation to verify that the proxy is being used for the requests.

Here's a more complete example:

import requests

# Proxy configuration
proxies = {
    "http": "http://user:pass@proxyserver:8080",
    "https": "http://user:pass@proxyserver:8080",
}

def fetch_data(url):
    try:
        response = requests.get(url, proxies=proxies)
        response.raise_for_status()
        return response.json()
    except requests.exceptions.RequestException as e:
        print(f"Error: {e}")
        return None

if __name__ == "__main__":
    url = "https://api.example.com/data"
    data = fetch_data(url)
    if data:
        print(data)

In this example, replace `http://user:pass@proxyserver:8080` with your actual proxy details.

If you need further assistance, feel free to ask!

Best, Alexander
